language: php
sudo: false
dist: trusty

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0

env:
  - WP_VERSION=latest WC_VERSION=latest
  - WP_VERSION=4.9.9 WC_VERSION=latest
  - WP_VERSION=4.9.9 WC_VERSION=3.4.7
  - WP_VERSION=4.9.9 WC_VERSION=3.3.5
  - WP_VERSION=4.9.9 WC_VERSION=3.2.6

# Considerations for the test matrix:
#
# - The "WC Requires At Least" is 3.2.6, so that's the lowest we need to go
# - WordPress < 5.0 doesn't officially support PHP 7.3.
# - WordPress 5.0 requires at least WooCommerce 3.5.1
matrix:
  fast_finish: true
  include:
    - name: Coding Standards
      php: 7.2
      env: WP_VERSION=latest WC_VERSION=latest RUN_PHPCS=1
    - name: Code Coverage
      php: 7.2
      env: WP_VERSION=latest WC_VERSION=latest RUN_CODE_COVERAGE=1
    - name: Bleeding Edge
      php: 7.3
      env: WP_VERSION=trunk WC_VERSION=latest
  exclude:
    - php: 7.3
      env: WP_VERSION=4.9.9 WC_VERSION=latest
    - php: 7.3
      env: WP_VERSION=4.9.9 WC_VERSION=3.4.7
    - php: 7.3
      env: WP_VERSION=4.9.9 WC_VERSION=3.3.5
    - php: 7.3
      env: WP_VERSION=4.9.9 WC_VERSION=3.2.6
  allow_failures:
    - name: Code Coverage
      php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=0 WC_VERSION=latest RUN_CODE_COVERAGE=1

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${RUN_CODE_COVERAGE} ]]; then
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.0/coveralls.phar
      chmod +x coveralls.phar
      mkdir -p build/logs
    fi
  - phpenv config-rm xdebug.ini
  - |
    if [[ ${GITHUB_AUTH_TOKEN} != '' ]]; then
      composer config -g github-oauth.github.com $GITHUB_AUTH_TOKEN
    fi
  - bash tests/bin/install-wp-tests.sh woocommerce_test root '' localhost $WP_VERSION
  - bash tests/bin/set-woocommerce-version.sh $WC_VERSION
  - composer install --prefer-source

script:
  - |
    if [[ ${RUN_CODE_COVERAGE} ]]; then
      phpdbg -qrr -d memory_limit=-1 ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=build/logs/clover.xml --exclude-group=timeout
    else
      ./vendor/bin/phpunit
    fi
  - |
    if [[ ${RUN_PHPCS} == 1 ]]; then
      ./vendor/bin/phpcs
    fi

after_success:
  - |
    if [[ ${RUN_CODE_COVERAGE} ]]; then
      travis_retry php coveralls.phar
    fi
