language: php
sudo: false
dist: trusty

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: WP_VERSION=trunk WP_MULTISITE=0 WC_VERSION=latest RUN_PHPCS=1
    - php: 7.2
      env: WP_VERSION=trunk WP_MULTISITE=1 WC_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=0 WC_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=0 WC_VERSION=3.2.6
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0 WC_VERSION=latest

  # The following WooCommerce core test currently fails in multisite, with or without this
  # plugin being active:
  #
  # WC_Tests_Setup_Functions::test_wizard_in_cart_payment_gateways()
  allow_failures:
    - php: 7.2
      env: WP_VERSION=trunk WP_MULTISITE=1 WC_VERSION=latest


before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - phpenv config-rm xdebug.ini
  - |
    if [[ ${GITHUB_AUTH_TOKEN} != '' ]]; then
      composer config -g github-oauth.github.com $GITHUB_AUTH_TOKEN
    fi
  - bash tests/bin/install-wp-tests.sh woocommerce_test root '' localhost $WP_VERSION
  - bash tests/bin/set-woocommerce-version.sh $WC_VERSION
  - composer install --prefer-source

script:
  - phpunit
  - |
    if [[ ${RUN_PHPCS} == 1 ]]; then
      ./vendor/bin/phpcs
    fi
